baseURL = 'http://josh.services/'
languageCode = 'en-gb'
[ Params ]
    title = 'Dangerous.Tech'
    description = 'Networking, Security and Code'
    author = 'Josh J'
    keywords = ['blog', 'devops', 'security']
    defaultTheme = 'dark'
