baseURL = 'https://josh.services/'
languageCode = 'en-gb'
title = 'Dangerous.Tech'
[ Params ]
    title = 'Dangerous.Tech'
    description = 'Networking, Security and Code'
    author = 'Josh J'
    keywords = ['blog', 'devops', 'security']
    defaultTheme = 'dark'
    showtoc = true
    ShowPostNavLinks = true

#[ menu ]
#    [ main ]
#        [ identifier.categories ]
#        name = 'categories'
#        url = '/categories/'
#        weight = 10
#        [ identifier.tags ]
#        name = 'tags'
#        url = '/tags/'
#        weight = 20